<?php
/**
 * @package    sauto
 * @subpackage Views
 * @author     Dacian Strain {@link http://shop.elbase.eu}
 * @author     Created on 17-Nov-2013
 * @license    GNU/GPL
 */

//-- No direct access
defined('_JEXEC') || die('=;)');
$db = JFactory::getDbo();
$user =& JFactory::getUser();
$uid = $user->id;

$app =& JFactory::getApplication();
$link_redirect = JRoute::_('index.php');
if ($uid == 0) {
	//vizitator
	$app->redirect($link_redirect, JText::_('SAUTO_PAGE_NOT_EXIST'));
} else {	
?>


<div id="wrapper9">
<h1><?php echo $this->site_title; ?></h1>
	<div id="side_bar">
	<?php 
			//verificare tip utilizator
			$query= "SELECT `tip_cont` FROM #__sa_profiles WHERE `uid` = '".$uid."'";
			$db->setQuery($query);
			$tip = $db->loadResult();
			if ($tip == 0) {
				//client
				$app->redirect($link_redirect, JText::_('SAUTO_PAGE_NOT_EXIST'));
			} elseif ($tip == 1) {
				//dealer
				require_once("components/com_sauto/assets/includes/menu_d.php");
			} else {
				//nedefinit, redirectionam la prima pagina
				$app->redirect($link_redirect, JText::_('SAUTO_PAGE_NOT_EXIST'));
			} 
		
	?> 
	</div>
				
	<div id="content9">
				<?php
			//verificare tip utilizator
			if ($tip == 1) {
				//dealer
//echo JPATH_BASE;


require_once("mobilpay/abstract.php");
require_once("mobilpay/card.php");
require_once("mobilpay/invoice.php");
require_once("mobilpay/address.php");
$baza = 'http://www.siteauto.ro';


$paymentUrl = 'http://sandboxsecure.mobilpay.ro';
//$paymentUrl = 'https://secure.mobilpay.ro';

$x509FilePath 	= '/home/rsit5498/public_html/final/components/com_sauto/views/pay/tmpl/certificates/public.cer';


#verificam daca private.key este fisier si daca exista fizic in sistem
/*$privateKeyFilePath = '/home/rsit5498/public_html/final/components/com_sauto/views/pay/tmpl/certificates/private.key';	
			$ck = '';
			//$fisier = $x509FilePath;
			$fisier = $privateKeyFilePath;
		if (is_file($fisier)) {
			$ck .= ' e bine <br />';
			if (file_exists($fisier)) {
			$ck .= ' exista ';
			} else {
			$ck .= ' nu exista ';
			}
		} else {
			$ck .= ' ceva nu este in regula ';
		}
		
		echo '>>>> '.$ck;
		*/
try
{
	srand((double) microtime() * 1000000);
	$objPmReqCard 						= new Mobilpay_Payment_Request_Card();
	#merchant account signature - generated by mobilpay.ro for every merchant account
	#semnatura contului de comerciant - mergi pe www.mobilpay.ro Admin -> Conturi de comerciant -> Detalii -> Setari securitate
	$objPmReqCard->signature 			= 'CVMG-8YLX-UDUH-PD7G-AVYV';
	#you should assign here the transaction ID registered by your application for this commercial operation
	#order_id should be unique for a merchant account
	$objPmReqCard->orderId 				= md5(uniqid(rand()));
	#below is where mobilPay will send the payment result. This URL will always be called first; mandatory
	$link_confirm = JRoute::_('index.php?option=com_sauto&view=pay&task=cc_confirm');
	$objPmReqCard->confirmUrl 			= $baza.$link_confirm; 
	#below is where mobilPay redirects the client once the payment process is finished. Not to be mistaken for a "successURL" nor "cancelURL"; mandatory
	$link_return = JRoute::_('index.php?option=com_sauto&view=pay&task=cc_return');
	$objPmReqCard->returnUrl 			= $baza.$link_return; 
	
	$item =& JRequest::getVar( 'item', '', 'post', 'string' );
	$uid =& JRequest::getVar( 'uid', '', 'post', 'string' );
	$valoare =& JRequest::getVar( 'valoare', '', 'post', 'string' );
	$moneda =& JRequest::getVar( 'moneda', '', 'post', 'string' );
	############
	
	$items = $item;
	
	#detalii cu privire la plata: moneda, suma, descrierea
	#payment details: currency, amount, description
	$objPmReqCard->invoice = new Mobilpay_Payment_Invoice();
	#payment currency in ISO Code format; permitted values are RON, EUR, USD, MDL; please note that unless you have mobilPay permission to 
	#process a currency different from RON, a currency exchange will occur from your currency to RON, using the official BNR exchange rate from that moment
	
	
	#and the customer will be presented with the payment amount in a dual currency in the payment page, i.e N.NN RON (e.ee EUR)
	$objPmReqCard->invoice->currency	= $moneda;
	$objPmReqCard->invoice->amount		= $valoare;
	#available installments number; if this parameter is present, only its value(s) will be available
	//$objPmReqCard->invoice->installments= '2,3';
	#selected installments number; its value should be within the available installments defined above
	//$objPmReqCard->invoice->selectedInstallments= '3';
	
	$objPmReqCard->invoice->details		= $items;
	
	#detalii cu privire la adresa posesorului cardului
	#details on the cardholder address (optional)
	$billingAddress 				= new Mobilpay_Payment_Address();
	$billingAddress->type			= $_POST['billing_type']; //should be "person"
	$billingAddress->firstName		= $_POST['billing_first_name'];
	$billingAddress->lastName		= $_POST['billing_last_name'];
	$billingAddress->address		= $_POST['billing_address'];
	$billingAddress->email			= $_POST['billing_email'];
	$billingAddress->mobilePhone		= $_POST['billing_mobile_phone'];
	$objPmReqCard->invoice->setBillingAddress($billingAddress);
	
	#detalii cu privire la adresa de livrare
	#details on the shipping address
	$shippingAddress 				= new Mobilpay_Payment_Address();
	$shippingAddress->type			= $_POST['shipping_type'];
	$shippingAddress->firstName		= $_POST['shipping_first_name'];
	$shippingAddress->lastName		= $_POST['shipping_last_name'];
	$shippingAddress->address		= $_POST['shipping_address'];
	$shippingAddress->email		= $_POST['shipping_email'];
	$shippingAddress->mobilePhone		= $_POST['shipping_mobile_phone'];
	$objPmReqCard->invoice->setShippingAddress($shippingAddress);

	#uncomment the line below in order to see the content of the request
	//echo "<pre>";print_r($objPmReqCard);echo "</pre>";
	//echo '>>> '.$x509FilePath;
	$objPmReqCard->encrypt($x509FilePath);
	
}
catch(Exception $e)
{
}

if(!($e instanceof Exception)):?>

<p>
	<form name="frmPaymentRedirect" method="post" action="<?php echo $paymentUrl;?>">
	<input type="hidden" name="env_key" value="<?php echo $objPmReqCard->getEnvKey();?>"/>
	<input type="hidden" name="data" value="<?php echo $objPmReqCard->getEncData();?>"/>
	<p>
		<?php echo JText::_('SA_REDIRECT_MSG_1'); ?>
	</p>
	<p>
		<?PHP ECHO jtEXT::_('SA_REDIRECT_MSG_2'); ?> <input type="image" src="mobilpay.gif" />
	</p>
	</form>
</p>
<!--
<script type="text/javascript" language="javascript">
	window.setTimeout(document.frmPaymentRedirect.submit(), 5000);
</script> -->
<?php else:?>
<p><strong><?php echo $e->getMessage();?></strong></p>
<?php endif;?>
<?php

			}
		?> 						
	</div>
				
					
</div>
<?php
}

